name: GitHub Action

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 22f3000690@ds.study.iitm.ac.in
      run: echo "Hello, world!"
